# -*- coding: utf-8 -*-
"""PED-A1-Moroni.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Vs-12iT8uLxxdyqLY9AukUQBfKC3tU0
"""

#Código Original:

class BombaCombustivel():

    def __init__(self, tipoCombustivel, valorLitro, quantidadeCombustivel):
        self.setTipoCombustivel(tipoCombustivel)
        self.setValorLitro(valorLitro)
        self.setQuantidadeCombustivel(quantidadeCombustivel)

    def setTipoCombustivel(self, tipoCombustivel):
        self.tipoCombustivel = tipoCombustivel

    def getTipoCombustivel(self):
        return self.tipoCombustivel 
        
    def setValorLitro(self, valorLitro):
        self.valorLitro = float(valorLitro)

    def setQuantidadeCombustivel(self, quantidadeCombustivel):
        self.quantidadeCombustivel = quantidadeCombustivel

    def abastecerPorValor(self, valor):
        totalLitros = valor / self.valorLitro
        if (totalLitros <= self.quantidadeCombustivel):
            self.setQuantidadeCombustivel(
                self.quantidadeCombustivel - totalLitros)

    def abastecerPorLitro(self, totalLitros):
        if (totalLitros <= self.quantidadeCombustivel):
            self.setQuantidadeCombustivel(
                self.quantidadeCombustivel - totalLitros)


def mudarCombustivel(bomba, tipoCombustivel):
    bomba.setTipoCombustivel(tipoCombustivel)
    print(f'Bomba utilizando {bomba.getTipoCombustivel()}')

    
# Teste da classe
bomba1 = BombaCombustivel('Gasolina Aditivada', 4.90, 10000)
bomba2 = BombaCombustivel('Alcool', 4.10, 5000)

while True:

    
    print("----------------------------POSTO TEXACO---------------------------")
    print("Bomba 1: ",bomba1.tipoCombustivel)
    print("Bomba 2: " ,bomba2.tipoCombustivel)
    print("-------------------------------------------------------------------")
    print("PREÇO GASOLINA",bomba1.valorLitro)
    print("PREÇO ALCOOL",bomba2.valorLitro)

    print('''
----------------------------
1- ALTERAR PREÇO
2- COLOCAR COMBUSTIVEL
3- ZERAR BOMBA
4- MUDAR COMBUSTIVEL DA BOMBA
5- SAIR
''')
    
    x = float(input("DIGITE A OPÇÃO DESEJADA: "))
    if x == 1:
        alterar = float(input("(1) ALTERAR PREÇO GASOLINA (2) ALTERAR PREÇO DO ALCOOL: "))

        if alterar == 1:
            n=float(input('Novo Preço: '))
            bomba1.setValorLitro(n)
            print("PREÇO DA GASOLINA ALTERADO PARA:",bomba1.valorLitro)


        if alterar == 2:
            n=float(input('Novo Preço: '))
            bomba2.setValorLitro(n)
            print("PREÇO DO ALCOOL ALTERADO PARA:",bomba2.valorLitro)


    if x == 2:

        colocar = float(input("(1) GASOLINA (2) ALCOOL: "))

        if colocar == 1:
            z = float(input("DIGITE VALOR DESEJADO: "))
            gasolina = bomba1.valorLitro
            print("VOCÊ ABASTECEU",z/gasolina,"L DE GASOLINA")


        if colocar == 2:
            r = float(input("DIGITE O VALOR DESEJADO: "))
            alcool = bomba2.valorLitro
            print("VOCÊ ABASTECEU,",r/alcool,"L DE ALCOOL")


    if x == 3:
        e=float(input("(1) ZERAR BOMBA DE GASOLINA (2) ZERAR BOMBA DE ALCOOL: "))

        if e == 1 :
            bomba1.quantidadeCombustivel = 0

        if e ==2:
            bomba2.quantidadeCombustivel = 0
            
    if x == 4:
        print("BOMBA 1:")
        comb=input("Combustivel: ")

        mudarCombustivel(bomba1,comb)

    if x == 5:
        break

#Código Corrigido:

class BombaCombustivel():

    def __init__(self, tipoCombustivel, valorLitro, quantidadeCombustivel):
        self.setTipoCombustivel(tipoCombustivel)
        self.setValorLitro(valorLitro)
        self.setQuantidadeCombustivel(quantidadeCombustivel)

    def setTipoCombustivel(self, tipoCombustivel):
        self.tipoCombustivel = tipoCombustivel

    def getTipoCombustivel(self):
        return self.tipoCombustivel 
        
    def setValorLitro(self, valorLitro):
        self.valorLitro = float(valorLitro)

    def setQuantidadeCombustivel(self, quantidadeCombustivel):
        self.quantidadeCombustivel = quantidadeCombustivel

    def abastecerPorValor(self, valor):
        totalLitros = valor / self.valorLitro
        if (totalLitros <= self.quantidadeCombustivel):
            self.setQuantidadeCombustivel(
                self.quantidadeCombustivel - totalLitros)

    def abastecerPorLitro(self, totalLitros):
        if (totalLitros <= self.quantidadeCombustivel):
            self.setQuantidadeCombustivel(
                self.quantidadeCombustivel - totalLitros)


def mudarCombustivel(bomba, tipoCombustivel):
    bomba.setTipoCombustivel(tipoCombustivel)
    print(f'Bomba utilizando {bomba.getTipoCombustivel()}')

    
# Teste da classe
bomba1 = BombaCombustivel('Gasolina Aditivada', 4.90, 10000)
bomba2 = BombaCombustivel('Alcool', 4.10, 5000)

while True:

    
    print("----------------------------POSTO TEXACO---------------------------")
    print("Bomba 1: ",bomba1.tipoCombustivel)
    print("Bomba 2: " ,bomba2.tipoCombustivel)
    print("-------------------------------------------------------------------")
    print("PREÇO", bomba1.tipoCombustivel,bomba1.valorLitro)
    print("PREÇO", bomba2.tipoCombustivel,bomba2.valorLitro)

    print('''
----------------------------
1- ALTERAR PREÇO
2- COLOCAR COMBUSTIVEL
3- ZERAR BOMBA
4- MUDAR COMBUSTIVEL DA BOMBA
5- SAIR
''')

#Alteradas as intancias em que o código dizia GASOLINA e ALCOOL sem verificar a variável global.
    
    x = float(input("DIGITE A OPÇÃO DESEJADA: "))
  
    if x == 1:
            
        alterar = float(input("(1) Alterar o preço de {}, (2) Alterar o preço de {}:" .format(bomba1.tipoCombustivel,bomba2.tipoCombustivel)))

        if alterar == 1:
            n=float(input('Novo Preço: '))
            bomba1.setValorLitro(n)
            print("Preço de {} alterado para {}:".format(bomba1.tipoCombustivel,bomba1.valorLitro))


        if alterar == 2:
            n=float(input('Novo Preço: '))
            bomba2.setValorLitro(n)
            print("Preço de {} alterado para {}:".format(bomba2.tipoCombustivel,bomba2.valorLitro))


    if x == 2:

        colocar = float(input("(1) {}, (2) {}:" .format(bomba1.tipoCombustivel,bomba2.tipoCombustivel)))

        if colocar == 1:
            z = float(input("DIGITE VALOR DESEJADO: "))
            gasolina = bomba1.valorLitro
            print("VOCÊ ABASTECEU",z/gasolina,"L DE",bomba1.tipoCombustivel )


        if colocar == 2:
            r = float(input("DIGITE O VALOR DESEJADO: "))
            alcool = bomba2.valorLitro
            print("VOCÊ ABASTECEU,",r/alcool,"L DE",bomba2.tipoCombustivel)


    if x == 3:
        e=float(input("(1) ZERAR BOMBA DE GASOLINA (2) ZERAR BOMBA DE ALCOOL: "))

        if e == 1 :
            bomba1.quantidadeCombustivel = 0

        if e ==2:
            bomba2.quantidadeCombustivel = 0

#Corrigido, agora pede para escolher qual bomba mudar ao invés de só dar a opção 1.         
   
    if x == 4:
        b=int(input('(1) ALTERAR BOMBA 1 (2) ALTERAR BOMBA 2: '))
        
        if b == 1:
          print("BOMBA 1:")
          comb=input("Combustivel: ")
          mudarCombustivel(bomba1,comb)
        
        elif b == 2:
          print("BOMBA 2:")
          comb=input("Combustivel: ")
          mudarCombustivel(bomba2,comb)

    if x == 5:
        break